### ISSUE TITLE
einops.rearrange算子加入到计算中

### ISSUE THREAD

**Issue by walking-shadow** [zugexiaodui/torch_flops#12]
我经常使用einops.rearrange来处理特征的形状，因为它使用简单，并且在代码上也更容易阅读，很多开源的代码也都在使用，你有计划把这个算子也加入到模型计算量的计算中吗

**Comment by zugexiaodui** [comment]
你好！rearrange并不影响计算量，因此如果遇到可以直接忽略的，只要torch.fx能编译通过就行。我没有测试torch.fx能否支持rearrange，如果不能的话本代码库也没办法实现，毕竟torch.fx是基础而且我修改不了~

**Comment by walking-shadow** [comment]
好的，谢谢啦，我已经把rearrange用view之类的命令替换掉了
