### ISSUE TITLE
how to count flops of a given torch.fx model based on this code?

### ISSUE THREAD

**Issue by MaltoseFlower** [zugexiaodui/torch_flops#13]
how to count flops of a given torch.fx model based on this code? Could you give me a demo?

**Comment by zugexiaodui** [comment]
You may try changing the following source code of `class TorchFLOPsByFX` from:
https://github.com/zugexiaodui/torch_flops/blob/dc72fb62934e107987fc3e9cb59d74d32b3910ef/torch_flops/flops_engine.py#L381-L383
to:
```python
# model.eval() 
 try: 
    # self.graph_model: GraphModule = symbolic_trace(model) 
    self.graph_model: GraphModule = model
```
