### ISSUE TITLE
问题报错

### ISSUE THREAD

**Issue by GJWZU** [zugexiaodui/torch_flops#14]
mask = torch.zeros(B, H, W).bool().to(self.token_projection.weight.device)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: zeros() received an invalid combination of arguments - got (Proxy, Proxy, Proxy), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

NOTE: The model cannot be built as a graph model by 'symbolic_trace()'. Please replace the `tensor.shape[i]` that servers as the parameter of a function with a pre-defined deterministic value.
 想请问博主这个问题 如何解决

**Comment by zugexiaodui** [comment]
在torch.fx中不能用索引[捂脸]，把B,H,W改为确定的数值而非根据shape运行时决定就可以了。可以参考[这个issue](https://github.com/zugexiaodui/torch_flops/issues/4)，也是类似的问题。

**Comment by GJWZU** [comment]
谢谢，当B，H，W确实需要变化时，是需要对代码进行更改，每次调用都需要给他一个固定的值确实有点不方便，但是依然感谢你的工作为我们提供一个新的方法。
