### ISSUE TITLE
the error from example1

### ISSUE THREAD

**Issue by BitCalSaul** [zugexiaodui/torch_flops#2]
I tried to run the example1.py but found this error. Also, it has been encountered when I create a linear model.
<img width="1142" alt="image" src="https://github.com/zugexiaodui/torch_flops/assets/142638691/d1692791-c430-4771-9fe7-f8d6242c18ae">

**Comment by BitCalSaul** [comment]
it seems like python 3.10 is necessary.

**Comment by zugexiaodui** [comment]
Yes, a new version of python is required. Sorry for forgetting to include the version instructions for Python.
