### ISSUE TITLE
memory profiler not work

### ISSUE THREAD

**Issue by BitCalSaul** [zugexiaodui/torch_flops#5]
Hi, I installed the newest version from pip using this command `pip install torch_flops -i https://pypi.org/simple`. While the last version's torch_flops could be imported in the script but not for the newest version. With the correct conda environment activated, the python throw an error as below:
<img width="664" alt="image" src="https://github.com/zugexiaodui/torch_flops/assets/142638691/a173c197-db31-484f-9aa0-da791691946d">

Thus, I git clone your repo and manually import the function. However, with the linear model tested, the memory profiler seems not working as below:
<img width="1282" alt="image" src="https://github.com/zugexiaodui/torch_flops/assets/142638691/f4b4a4b2-82ef-45df-b0ec-1ad0ef789282">
Considering the model and tensor are in the GPU, there should be some value instead of 0.

**Comment by zugexiaodui** [comment]
You can try `pip install torch_flops -i https://pypi.org/simple --upgrade`  to install a new version. I will fix this import error in the next version.

As to the memory profiler, could you please share your code here?

**Comment by BitCalSaul** [comment]
Hi I tried this command but it still has this error:
<img width="804" alt="image" src="https://github.com/zugexiaodui/torch_flops/assets/142638691/18c13b4a-5e58-4a53-8ec0-7977e902678c">

For the memory profiler, I found if you put the model to torch.device('cuda:0'), it would be correct, while incorrect for other GPUs.

**Comment by zugexiaodui** [comment]
Sorry for the late update of the version. I just uploaded the new codes and fixed the import error. You can update the lib to v0.3.4 now.

The default GPU is 'cuda:0' and I didn't change it, so it only supports for 'cuda:0'. However, you can use 'CUDA_VISIBLE_DEVICES' to specify which GPU to use, and the specified GPU will be regarded as 'cuda:0'.

**Comment by zugexiaodui** [comment]
And the new version supports for peak memory, which is an option of `TorchFLOPsByFX` class.

**Comment by zugexiaodui** [comment]
The bug of "cuda!= 0" has been fixed in the version 0.3.5.

**Comment by BitCalSaul** [comment]
Thanks the package could be imported properly. And the time and max memory used are both printable.
